Repository googleapis/nodejs-resource-manager, pull requests merged in 2021-05, with the labels that each got.

#370 feat: package rename in npm
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs.cfg
  .kokoro/release/publish.cfg
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  package.json
  samples/package.json
Labels: api: cloudresourcemanager, cla: yes

#371 build: remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudresourcemanager, cla: yes, context: full, kokoro:force-run

#372 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/generated-files-bot.yml
  .jsdoc.js
  .kokoro/common.cfg
  .repo-metadata.json
  README.md
  samples/README.md
  synth.metadata
  synth.py
Labels: api: cloudresourcemanager, automerge, cla: yes
